-- Create system_announcements table for Admin (bao.lt) notifications
CREATE TABLE IF NOT EXISTS public.system_announcements (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    type TEXT DEFAULT 'info' CHECK (type IN ('maintenance', 'update', 'info', 'warning')),
    is_active BOOLEAN DEFAULT true,
    created_by TEXT DEFAULT 'bao.lt',
    created_at TIMESTAMPTZ DEFAULT now(),
    expires_at TIMESTAMPTZ NULL
);

-- Enable Row Level Security
ALTER TABLE public.system_announcements ENABLE ROW LEVEL SECURITY;

-- Allow read access for active announcements
CREATE POLICY "Allow public read active announcements" 
ON public.system_announcements FOR SELECT 
USING (true);

-- Allow full access for anon insert/update/delete
CREATE POLICY "Allow anon insert/update/delete announcements" 
ON public.system_announcements FOR ALL 
USING (true) WITH CHECK (true);
