-- =============================================================================
-- SQL SETUP SCRIPT FOR TABLE: cong_viec
-- Run this script in Supabase SQL Editor to initialize task & reminder table
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.cong_viec (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tieu_de TEXT NOT NULL,
    ghi_chu TEXT,
    ngay_hen TIMESTAMPTZ NOT NULL,
    uu_tien TEXT NOT NULL DEFAULT 'trung_binh',
    trang_thai TEXT NOT NULL DEFAULT 'cho_xu_ly',
    da_nhac_hen BOOLEAN DEFAULT FALSE,
    user_created TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (RLS)
ALTER TABLE public.cong_viec ENABLE ROW LEVEL SECURITY;

-- Allow read/write access to anon & authenticated users
DROP POLICY IF EXISTS "Allow all access to cong_viec" ON public.cong_viec;
CREATE POLICY "Allow all access to cong_viec" ON public.cong_viec
    FOR ALL USING (true) WITH CHECK (true);
